version: "3.5"

services:
    fate:
        container_name: fate
        build:
            context: ./fate
            dockerfile: ./Dockerfile
        ports:
            - "80:80"
        depends_on:
            - "amnesia"
            - "bleach"
        env_file: './fate/.env'

    bleach:
        container_name: bleach
        build:
            context: ./bleach
            dockerfile: ./Dockerfile
        ports:
            - "8080:8080"
        depends_on:
            - "amnesia"
        env_file: './bleach/.env'

    amnesia:
        container_name: amnesia
        build:
            context: ./amnesia
            dockerfile: ./Dockerfile
        ports:
            - "5000:5000"
